# Generated by Django 5.2.5 on 2025-09-14 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_category_options_alter_news_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_favourite_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.news')),
            ],
            options={
                'verbose_name_plural': 'Новость',
            },
        ),
    ]
