# Generated by Django 5.2.5 on 2025-09-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='user_favourite_have',
            field=models.BooleanField(default=False),
        ),
    ]
