# Generated by Django 5.2.5 on 2025-09-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_favourite_user_favourite_have'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={'verbose_name_plural': 'Избранное'},
        ),
        migrations.RenameField(
            model_name='favourite',
            old_name='user_favourite_news',
            new_name='favourite_news',
        ),
        migrations.RenameField(
            model_name='favourite',
            old_name='user_favourite_have',
            new_name='have_favourite',
        ),
    ]
